### ISSUE TITLE
Switch to kernel plugin

### ISSUE THREAD

**Issue by MERLev** [MERLev/remaPSV2#8]
Would allow to draw plugin menu everywhere
Would add LiveArea and system apps support
Would add ability to remap system keys (VOLUME, HOME, POWER)
Would (pbly) solve memory issues when many plugins are loaded

**Comment by dkrmdi** [comment]
This is a very desired feature, because we want to change the volume or mute the vita instantly using DS4. 

Example: We are using udcd uvc and ds4vita plugins. Vita is not on our hands, and it a nuisance to pick it up to change the volume. Maybe make L2 and R2 correspond to vol up and vol down button. So we can change or mute volume using only DS4 buttons.

**Comment by MERLev** [comment]
Volume buttons remap and emulation is actually already working in latest kernel builds. Unfortunately, I have a lot of issues with external controllers and gyroscope.

**Comment by MERLev** [comment]
Implemented in reVita. Sys buttons support is not full though.

**Comment by dkrmdi** [comment]
Thank you. I am totally satiafies with this.
